name: CD

on:
  push:
    branches: [main]

jobs:
  pre-cd:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: pre-cd
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_DEPLOY_HOOK }}
          method: 'GET'
